export interface EquipmentSpecifications {
  manufacturer?: string
  model?: string
  year?: number
  capacity?: string
  power?: string
  voltage?: string
  hours?: string
  condition?: string
  weight?: string
  dimensions?: string
  liftingHeight?: string
  engine?: string
  suction?: string
  discharge?: string
  flow?: string
  head?: string
  size?: string
  alternator?: string
  delivery?: string
  flag?: string
  motorPower?: string
  insideClearWidth?: string
  type?: string
  lightCoverage?: string
  runtime?: string
  silentMode?: string
  powerType?: string
  batteryCapacity?: string
  batteryRechargeTime?: string
  illuminatedArea?: string
  batteryRuntime?: string
  solarPanels?: string
  dimensionsL?: string
  dimensionsW?: string
  dimensionsH?: string
  emissions?: string
  volt?: string
  engineModel?: string
  kVAPrime?: string
  phase?: string
  engineHours?: string
  current?: string
  maxFlow?: string
  suctionSize?: string
  dischargeSize?: string
  solidsHandling?: string
  drive?: string
  kilowatts?: string
  fuelCapacity?: string
  maxHead?: string
  fuel?: string
  floodlights?: string
  dimensionsMinLxWxH?: string
  dimensionsMaxLxWxH?: string
  co2Reduction?: string
  runningTime?: string
  quantity?: number
  usage?: string
  wheelAxis?: string
  clearInsideWidth?: string
  translationSpeed?: string
  groundPressure?: string
  steeringRadius?: string
  location?: string
  span?: string
  hoistingHeight?: string
  hoistType?: string
  control?: string
  mainVoltage?: string
  gauge?: string
  trackCentre?: string
  heightAtHook?: string
  maxHeight?: string
  make?: string
  kVAStandby?: string
  engineMake?: string
  alternatorMake?: string
  alternatorModel?: string
  controlPanel?: string
  frequency?: string
  housing?: string
}

export interface Equipment {
  id: string
  slug: string
  name: string
  shortDescription: string
  longDescription: string
  price: string
  category: 'cranes' | 'generators' | 'pumps' | 'trailers' | 'tower-lights' | 'engines'
  manufacturer: string
  images: string[]
  specifications: EquipmentSpecifications
  highlights: string[]
  featured?: boolean
}

export type EquipmentFilter = {
  category?: Equipment['category']
  manufacturer?: string
}