export interface EquipmentSpecifications {
  manufacturer?: string
  model?: string
  year?: number
  capacity?: string
  power?: string
  voltage?: string
  hours?: string
  condition?: string
  serialNumber?: string
  weight?: string | number
  dimensions?: string
  liftingHeight?: string
  engine?: string
  suction?: string
  discharge?: string
  flow?: string
  head?: string
  size?: string
  alternator?: string
  delivery?: string
  flag?: string
  motorPower?: string
  insideClearWidth?: string
  type?: string
  lightCoverage?: string
  runtime?: string
  silentMode?: string
  powerType?: string
  batteryCapacity?: string
  batteryRechargeTime?: string
  illuminatedArea?: string
  batteryRuntime?: string
  solarPanels?: string
  dimensionsL?: string
  dimensionsW?: string
  dimensionsH?: string
  emissions?: string
  volt?: string
  engineModel?: string
  kVAPrime?: string
  phase?: string
  engineHours?: string
  current?: string
  maxFlow?: string
  suctionSize?: string
  dischargeSize?: string
  solidsHandling?: string
  drive?: string
  kilowatts?: string
  fuelCapacity?: string | number
  maxHead?: string
  dwt?: string
  dwcc?: string
  yearBuilt?: number
  yearRebuilt?: number
  grt?: string
  nrt?: string
  lengthOverall?: string
  breadthMoulded?: string
  depthMoulded?: string
  generators?: string
  class?: string
  frameType?: string
  saddlePads?: string
  fuel?: string
  payload?: string
  deadWeight?: string
  totalWeight?: string
  axleLines?: number
  driveAxles?: number
  steeredBogies?: number
  rpm?: string
  use?: string
  floodlights?: string
  dimensionsMinLxWxH?: string
  dimensionsMaxLxWxH?: string
  co2Reduction?: string
  runningTime?: string
  quantity?: number
  usage?: string
  wheelAxis?: string
  clearInsideWidth?: string
  translationSpeed?: string
  groundPressure?: string
  steeringRadius?: string
  location?: string
  span?: string
  hoistingHeight?: string
  hoistType?: string
  control?: string
  mainVoltage?: string
  gauge?: string
  trackCentre?: string
  heightAtHook?: string
  maxHeight?: string
  make?: string
  kVAStandby?: string
  engineMake?: string
  alternatorMake?: string
  alternatorModel?: string
  controlPanel?: string
  frequency?: string
  housing?: string
  seats?: number
  exteriorColor?: string
  transmission?: string
  bodyType?: string
  previousOwners?: number
  engineSize?: string
  registrationDate?: string
  doors?: number
  interiorTrim?: string
  driveType?: string
  franchiseApproved?: string
  serviceHistory?: string
  ulezCompliant?: string
  startStop?: string
  insuranceGroup?: number
  bhp?: number
  enginePowerPS?: number
  acceleration060?: number
  maxSpeed?: number
  mpgCombined?: number
  co2?: number
  torque?: number
  height?: number
  kerbWeight?: number
  length?: number
  width?: number
  stroke?: number
  cylinders?: number
  valvesPerCylinder?: number
  forwardGears?: number
  grossWeight?: number
}

export interface Equipment {
  id: string
  slug: string
  name: string
  shortDescription: string
  longDescription: string
  price: string
  category: 'cranes' | 'generators' | 'pumps' | 'trailers' | 'tower-lights' | 'engines' | 'mobile-boat-hoists' | 'luxury-vehicles'
  manufacturer: string
  images: string[]
  specifications: EquipmentSpecifications
  highlights: string[]
  featured?: boolean
}

export type EquipmentFilter = {
  category?: Equipment['category']
  manufacturer?: string
}